spring.application.name=kready

server.port:8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.hovuroacnwtarmbszjns&password=Kready_2026!
spring.datasource.username=postgres.hovuroacnwtarmbszjns
spring.datasource.password=Kready_2026!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Ordina i gruppi di tag alfabeticamente
springdoc.swagger-ui.tags-sorter=alpha

# Ordina le operazioni all'interno di ogni gruppo per metodo HTTP
springdoc.swagger-ui.operations-sorter=method