spring.application.name=kready

# URL di connessione: localhost porta 3306, database 'kready'
spring.datasource.url=jdbc:mysql://localhost:3306/kready?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Credenziali predefinite di XAMPP
spring.datasource.username=root
spring.datasource.password=

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Ordina i gruppi di tag alfabeticamente
springdoc.swagger-ui.tags-sorter=alpha

# Ordina le operazioni all'interno di ogni gruppo per metodo HTTP
springdoc.swagger-ui.operations-sorter=method